openapi: 3.0.0
paths:
  /api:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: Title
  description: The API Description
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas: {}
externalDocs:
  description: 外部API設計書などのURL
  url: 'url: string'
